import p1_img from "/product_1.png";
import p2_img from "/product_2.png";
import p3_img from "/product_3.png";
import p4_img from "/product_4.png";
import p5_img from "/product_5.png";
import p6_img from "/product_6.png";
import p7_img from "/product_7.png";
import p8_img from "/product_8.png";
import p9_img from "/product_9.png";
import p10_img from "/product_10.png";
import p11_img from "/product_11.png";
import p12_img from "/product_12.png";
import p13_img from "/product_13.png";
import p14_img from "/product_14.png";
import p15_img from "/product_15.png";
import p16_img from "/product_16.png";
import p17_img from "/product_17.png";
import p18_img from "/product_18.png";
import p19_img from "/product_19.png";
import p20_img from "/product_20.png";
import p21_img from "/product_21.png";
import p22_img from "/product_22.png";
import p23_img from "/product_23.png";
import p24_img from "/product_24.png";
import p25_img from "/product_25.png";
import p26_img from "/product_26.png";
import p27_img from "/product_27.png";
import p28_img from "/product_28.png";
import p29_img from "/product_29.png";
import p30_img from "/product_30.png";
import p31_img from "/product_31.png";
import p32_img from "/product_32.png";
import p33_img from "/product_33.png";
import p34_img from "/product_34.png";
import p35_img from "/product_35.png";
import p36_img from "/product_36.png";

// let all_product = [
//   {
//     id: 1,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p1_img,
//     new_price: 50.0,
//     old_price: 80.5,
//   },
//   {
//     id: 2,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p2_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 3,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p3_img,
//     new_price: 60.0,
//     old_price: 100.5,
//   },
//   {
//     id: 4,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p4_img,
//     new_price: 100.0,
//     old_price: 150.0,
//   },
//   {
//     id: 5,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p5_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 6,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p6_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 7,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p7_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 8,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p8_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 9,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p9_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 10,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p10_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 11,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p11_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 12,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "women",
//     image: p12_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 13,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p13_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 14,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p14_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 15,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p15_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 16,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p16_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 17,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p17_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 18,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p18_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 19,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p19_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 20,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p20_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 21,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p21_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 22,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p22_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 23,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p23_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 24,
//     name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
//     category: "men",
//     image: p24_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 25,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p25_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 26,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p26_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 27,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p27_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 28,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p28_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 29,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p29_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 30,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p30_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 31,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p31_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 32,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p32_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 33,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p33_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 34,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p34_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 35,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p35_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 36,
//     name: "Boys Orange Colourblocked Hooded Sweatshirt",
//     category: "kid",
//     image: p36_img,
//     new_price: 85.0,
//     old_price: 120.5,
//   },
// ];

const all_product = [
  // Women's Products
  {
    id: 1,
    name: "Casual Striped V-Neck Blouse",
    category: "women",
    image: p1_img,
    new_price: 1250.0,
    old_price: 1750.0,
    sizes: [
      { id: 1, size: "XS" },
      { id: 2, size: "S" },
      { id: 3, size: "M" },
      { id: 4, size: "L" },
      { id: 5, size: "XL" },
      { id: 6, size: "XXL" },
    ],
  },
  {
    id: 2,
    name: "Floral Print Wrap Dress",
    category: "women",
    image: p2_img,
    new_price: 1500.0,
    old_price: 1800.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
      { id: 4, size: "XXL" },
    ],
  },
  {
    id: 3,
    name: "Polka Dot Peplum Top",
    category: "women",
    image: p3_img,
    new_price: 1350.0,
    old_price: 1950.0,
    sizes: [
      { id: 1, size: "XS" },
      { id: 2, size: "S" },
      { id: 3, size: "XXL" },
    ],
  },
  {
    id: 4,
    name: "Chiffon Ruffle Hem Blouse",
    category: "women",
    image: p4_img,
    new_price: 1450.0,
    old_price: 1750.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
      { id: 3, size: "L" },
    ],
  },
  {
    id: 5,
    name: "Solid Color Turtleneck Sweater",
    category: "women",
    image: p5_img,
    new_price: 1600.0,
    old_price: 1900.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
  },
  {
    id: 6,
    name: "Lace Trimmed Silk Blouse",
    category: "women",
    image: p6_img,
    new_price: 1550.0,
    old_price: 1850.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
      { id: 4, size: "XXL" },
    ],
  },
  {
    id: 7,
    name: "Boho Style Off-Shoulder Top",
    category: "women",
    image: p7_img,
    new_price: 1300.0,
    old_price: 1700.0,
    sizes: [
      { id: 1, size: "XS" },
      { id: 2, size: "S" },
      { id: 3, size: "M" },
    ],
  },
  {
    id: 8,
    name: "Classic Button-Down Shirt",
    category: "women",
    image: p8_img,
    new_price: 1400.0,
    old_price: 1800.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XXL" },
    ],
  },
  {
    id: 9,
    name: "Cotton Bell Sleeve Top",
    category: "women",
    image: p9_img,
    new_price: 1250.0,
    old_price: 1600.0,
    sizes: [
      { id: 1, size: "XS" },
      { id: 2, size: "M" },
      { id: 3, size: "XL" },
    ],
  },
  {
    id: 10,
    name: "Floral Embroidered Tunic",
    category: "women",
    image: p10_img,
    new_price: 1500.0,
    old_price: 1750.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "L" },
      { id: 3, size: "XXL" },
    ],
  },
  {
    id: 11,
    name: "Casual Loose Fit Blouse",
    category: "women",
    image: p11_img,
    new_price: 1400.0,
    old_price: 1700.0,
    sizes: [
      { id: 1, size: "XS" },
      { id: 2, size: "S" },
      { id: 3, size: "M" },
      { id: 4, size: "XXL" },
    ],
  },
  {
    id: 12,
    name: "Knitted Round Neck Sweater",
    category: "women",
    image: p12_img,
    new_price: 1600.0,
    old_price: 1950.0,
    sizes: [
      { id: 1, size: "L" },
      { id: 2, size: "XL" },
      { id: 3, size: "XXL" },
    ],
  },

  // Men's Products
  {
    id: 13,
    name: "Men's Casual Bomber Jacket",
    category: "men",
    image: p13_img,
    new_price: 1750.0,
    old_price: 1900.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
  },
  {
    id: 14,
    name: "Men's Denim Jacket",
    category: "men",
    image: p14_img,
    new_price: 1650.0,
    old_price: 1850.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
      { id: 3, size: "XXL" },
    ],
  },
  {
    id: 15,
    name: "Men's Leather Motorcycle Jacket",
    category: "men",
    image: p15_img,
    new_price: 1800.0,
    old_price: 1990.0,
    sizes: [
      { id: 1, size: "L" },
      { id: 2, size: "XL" },
      { id: 3, size: "XXL" },
    ],
  },
  {
    id: 16,
    name: "Men's Hooded Sweatshirt",
    category: "men",
    image: p16_img,
    new_price: 1500.0,
    old_price: 1750.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
      { id: 3, size: "L" },
    ],
  },
  {
    id: 17,
    name: "Men's Slim Fit Polo Shirt",
    category: "men",
    image: p17_img,
    new_price: 1350.0,
    old_price: 1650.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
  },
  {
    id: 18,
    name: "Men's Quilted Jacket",
    category: "men",
    image: p18_img,
    new_price: 1450.0,
    old_price: 1750.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XXL" },
    ],
  },
  {
    id: 19,
    name: "Men's Zip-Up Hoodie",
    category: "men",
    image: p19_img,
    new_price: 1200.0,
    old_price: 1500.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
    ],
  },
  {
    id: 20,
    name: "Men's Long Sleeve Henley",
    category: "men",
    image: p20_img,
    new_price: 1100.0,
    old_price: 1400.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
      { id: 3, size: "XXL" },
    ],
  },
  {
    id: 21,
    name: "Men's Long Sleeve Henley",
    category: "men",
    image: p21_img,
    new_price: 1100.0,
    old_price: 1400.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
      { id: 3, size: "XXL" },
    ],
  },
  {
    id: 22,
    name: "Men's Casual Joggers",
    category: "men",
    image: p22_img,
    new_price: 1400.0,
    old_price: 1700.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
    ],
  },
  {
    id: 23,
    name: "Men's Knit Polo Shirt",
    category: "men",
    image: p23_img,
    new_price: 1250.0,
    old_price: 1500.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
  },
  {
    id: 24,
    name: "Men's Wool Overcoat",
    category: "men",
    image: p24_img,
    new_price: 2200.0,
    old_price: 2700.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
    ],
  },

  // Kids' Products
  {
    id: 25,
    name: "Kids' Cotton T-Shirt",
    category: "kid",
    image: p25_img,
    new_price: 750.0,
    old_price: 900.0,
    sizes: [
      { id: 1, size: "XS" },
      { id: 2, size: "S" },
      { id: 3, size: "M" },
    ],
  },
  {
    id: 26,
    name: "Kids' Printed Sweatshirt",
    category: "kid",
    image: p26_img,
    new_price: 850.0,
    old_price: 1000.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
    ],
  },
  {
    id: 27,
    name: "Kids' Denim Jacket",
    category: "kid",
    image: p27_img,
    new_price: 1300.0,
    old_price: 1600.0,
    sizes: [
      { id: 1, size: "XS" },
      { id: 2, size: "S" },
    ],
  },
  {
    id: 28,
    name: "Kids' Graphic Hoodie",
    category: "kid",
    image: p28_img,
    new_price: 950.0,
    old_price: 1200.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
    ],
  },
  {
    id: 29,
    name: "Kids' Colorblock Hoodie",
    category: "kid",
    image: p29_img,
    new_price: 900.0,
    old_price: 1100.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
      { id: 3, size: "L" },
    ],
  },
  {
    id: 30,
    name: "Kids' Striped Sweater",
    category: "kid",
    image: p30_img,
    new_price: 950.0,
    old_price: 1150.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
    ],
  },
  {
    id: 31,
    name: "Kids' Quilted Vest",
    category: "kid",
    image: p31_img,
    new_price: 1100.0,
    old_price: 1400.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
    ],
  },
  {
    id: 32,
    name: "Kids' Casual Joggers",
    category: "kid",
    image: p32_img,
    new_price: 800.0,
    old_price: 1000.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
      { id: 3, size: "L" },
    ],
  },
  {
    id: 33,
    name: "Kids' Plaid Shirt",
    category: "kid",
    image: p33_img,
    new_price: 950.0,
    old_price: 1200.0,
    sizes: [
      { id: 1, size: "XS" },
      { id: 2, size: "S" },
      { id: 3, size: "M" },
    ],
  },
  {
    id: 34,
    name: "Kids' Colorblock Hoodie",
    category: "kid",
    image: p34_img,
    new_price: 900.0,
    old_price: 1100.0,
    sizes: [
      { id: 1, size: "S" },
      { id: 2, size: "M" },
    ],
  },
  {
    id: 35,
    name: "Kids' Quilted Vest",
    category: "kid",
    image: p35_img,
    new_price: 1100.0,
    old_price: 1400.0,
    sizes: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
    ],
  },
  {
    id: 36,
    name: "Kids' Denim Jacket",
    category: "kid",
    image: p36_img,
    new_price: 1300.0,
    old_price: 1600.0,
    sizes: [
      { id: 1, size: "XS" },
      { id: 2, size: "S" },
    ],
  },
];

export default all_product;
